In [3]:
import numpy as np
# --- Task 1: Creating Arrays ---
print("--- Task 1: Creating Arrays ---")

array_1d = np.arange(1, 11)
print("\n1. 1D Array (1 to 10):\n", array_1d)


--- Task 1: Creating Arrays ---

1. 1D Array (1 to 10):
 [ 1  2  3  4  5  6  7  8  9 10]


In [4]:

array_2d = np.arange(1, 10).reshape(3, 3)
print("\n2. 2D Array (3x3 from 1-9):\n", array_2d)



2. 2D Array (3x3 from 1-9):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:

array_3d = np.random.rand(3, 5, 3)
print("\n3. 3D Random Array (3x5x3):\n", array_3d)


3. 3D Random Array (3x5x3):
 [[[0.45113847 0.55570109 0.65915959]
  [0.95274995 0.94096505 0.98397437]
  [0.50691651 0.95584054 0.72239942]
  [0.9097199  0.95014621 0.74953393]
  [0.15874749 0.13263604 0.49548974]]

 [[0.87649383 0.0891443  0.43074427]
  [0.85446229 0.40612978 0.47049348]
  [0.25564091 0.07285609 0.09692111]
  [0.14666116 0.48523394 0.8114887 ]
  [0.35221237 0.40928032 0.87050895]]

 [[0.994575   0.10557977 0.46106313]
  [0.30111255 0.42765738 0.46120847]
  [0.09456606 0.76683231 0.00533187]
  [0.94227902 0.97764416 0.45837906]
  [0.55202853 0.29712209 0.52978258]]]


In [6]:
print("\n--- Array Properties ---")
print(f"1D Array -> Shape: {array_1d.shape}, Size: {array_1d.size}, Datatype: {array_1d.dtype}")
print(f"2D Array -> Shape: {array_2d.shape}, Size: {array_2d.size}, Datatype: {array_2d.dtype}")
print(f"3D Array -> Shape: {array_3d.shape}, Size: {array_3d.size}, Datatype: {array_3d.dtype}")


--- Array Properties ---
1D Array -> Shape: (10,), Size: 10, Datatype: int64
2D Array -> Shape: (3, 3), Size: 9, Datatype: int64
3D Array -> Shape: (3, 5, 3), Size: 45, Datatype: float64
