In [1]:
import numpy as np

In [14]:
linspace_arr = np.linspace(0, 1, 10)
print("\n10 equally spaced values between 0 and 1:\n", linspace_arr)
print()


10 equally spaced values between 0 and 1:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]



In [4]:
identity_matrix = np.identity(4)
print("\n4x4 Identity Matrix:\n", identity_matrix)


4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
rand_arr_20 = np.random.randint(1, 101, 20)
print("Generated 1D array of 20 random integers:\n", rand_arr_20)
print()

Generated 1D array of 20 random integers:
 [80 44 98 85 19 93  9 28 71 84 85 83 28 43 54 44  3  6  9 39]



In [13]:
sorted_arr = np.sort(rand_arr_20)
print("Sorted array:\n", sorted_arr)
print()

Sorted array:
 [ 3  6  9  9 19 28 28 39 43 44 44 54 71 80 83 84 85 85 93 98]



In [9]:
five_largest = sorted_arr[-5:]
print("5 largest elements:", five_largest)

5 largest elements: [67 67 74 90 91]
