In [2]:
print("\n\n--- Task 4: Reshaping and Transposing ---")



--- Task 4: Reshaping and Transposing ---


In [3]:
import numpy as np

In [4]:
arrx = np.arange(1, 13)
print("\nOriginal 1D Array (1-12):\n", arrx)


Original 1D Array (1-12):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
reshaped_2d = arrx.reshape(4, 3)
print("\nReshaped to 2D (4x3):\n", reshaped_2d)


Reshaped to 2D (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
reshaped_3d = arrx.reshape(2, 2, 3)
print("\nReshaped to 3D (2x2x3):\n", reshaped_3d)


Reshaped to 3D (2x2x3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
transposed_2d = reshaped_2d.T
print("\nTransposed 2D array:\n", transposed_2d)
print("Shape of transposed array:", transposed_2d.shape)


Transposed 2D array:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape of transposed array: (3, 4)
